export const MAX_WHEEL_PCT=.5,RESERVE_PCT=.1;
export const checklist=[['thesis','I can explain why I want to own the shares'],['cash','Cash is settled and available'],['liquidity','Average volume and open interest are healthy'],['price','I accept assignment at this strike'],['earnings','Earnings / dividend dates checked'],['iv','Implied volatility is not an unexplained spike'],['risk','Max loss and exit plan are written'],['size','Position stays within account sizing limits'],['basis','No premium is counted as collateral'],['roll','A roll trigger is defined before entry'],['event','Corporate actions reviewed'],['tax','Tax lot treatment understood'],['spread','Bid/ask spread is acceptable'],['diversify','Concentration remains reasonable'],['time','I can monitor expiration'],['manual','Unavailable market data is marked manual'],['paper','This account is correctly segregated'],['consent','I confirm this is planning, not a trade instruction']];
export function validateSize({accountValue,shares,strike}){const max=accountValue*MAX_WHEEL_PCT,reserve=accountValue*RESERVE_PCT,collateral=Math.max(0,shares)*Math.max(0,strike);return{ok:collateral<=max,collateral,max,reserve,remaining:accountValue-collateral-reserve,reason:collateral>max?`Collateral $${collateral.toFixed(2)} exceeds 50% wheel limit ($${max.toFixed(2)}).`:''}}
export function coveredCallCollateral(shares,strike){return Math.max(0,shares)*Math.max(0,strike)}
export function cashSecuredPutCollateral(contracts,strike){return Math.max(0,contracts)*Math.max(0,strike)*100}
export function partialClose(position,contracts,price){if(contracts<=0||contracts>position.openContracts)throw Error('Close quantity must be positive and no greater than open contracts');const realized=(position.entryPrice-price)*contracts*100;return{...position,openContracts:position.openContracts-contracts,realizedPnl:(position.realizedPnl||0)+realized,status:position.openContracts-contracts===0?'closed':'partial'}}
export function roll(position,newStrike,newExpiry,closePrice,openPrice){if(!newStrike||!newExpiry||closePrice<0||openPrice<0)throw Error('Invalid roll values');const qty=position.openContracts,closed=partialClose(position,qty,closePrice);return{...closed,status:'rolled',roll:{from:{strike:position.strike,expiry:position.expiry},to:{strike:newStrike,expiry:newExpiry},netCredit:(closePrice-openPrice)*qty*100},strike:newStrike,expiry:newExpiry,entryPrice:openPrice,openContracts:qty}}
export function rollCalculator({contracts=1,oldPremium=0,closeDebit=0,newPremium=0}){const qty=Number(contracts)||0;return{oldPremiumTotal:qty*oldPremium*100,closeDebitTotal:qty*closeDebit*100,newPremiumTotal:qty*newPremium*100,netCredit:qty*(oldPremium-closeDebit+newPremium)*100,breakevenChange:newPremium-closeDebit}}
export function scenarioThresholds({entryPrice,putStrike,callStrike,shares=100}){const s=Number(entryPrice)||0,p=Number(putStrike)||0,c=Number(callStrike)||0;return{assignmentAtOrBelow:p,callAwayAtOrAbove:c,maxLossPerShare:Math.max(0,s-p),capitalRequired:Math.max(0,p*shares),upsideToCall:c>0?((c-s)/s)*100:null}}
export function applyEvent(state,event){const next=structuredClone(state);next.events=[...(next.events||[]),event];if(event.type==='ADD_WHEEL')next.wheels.push(event.wheel);if(event.type==='UPDATE_WHEEL')next.wheels=next.wheels.map(w=>w.id===event.id?{...w,...event.patch}:w);if(event.type==='DELETE_WHEEL')next.wheels=next.wheels.filter(w=>w.id!==event.id);return next}
export function equity({cash,positions,marks={}}){let value=cash;for(const p of positions){const mark=marks[p.symbol];if(mark==null)return{value:null,unknown:[p.symbol]};value+=p.qty*mark}return{value,unknown:[]}}
export function validateImport(payload){if(!payload||payload.version!==1||!Array.isArray(payload.wheels)||!Array.isArray(payload.events))throw Error('Invalid Wheel Desk backup: expected version 1, wheels, and events');return payload}
export function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
export function toCsv(rows){if(!rows.length)return '';const keys=[...new Set(rows.flatMap(Object.keys))];const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;return [keys.join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n')}
